// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNpNxi4xczl7RqI1al8cVbvr-ttkWNOFk',
    appId: '1:860153483862:web:f2da9be1672a32f5dce1f7',
    messagingSenderId: '860153483862',
    projectId: 'todoapp-c455a',
    authDomain: 'todoapp-c455a.firebaseapp.com',
    storageBucket: 'todoapp-c455a.firebasestorage.app',
    measurementId: 'G-YD4641J3QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIR1QrBakXjG-B4F9GdcGfsoLPJxBgkfM',
    appId: '1:860153483862:android:7c35ff687fe1eddadce1f7',
    messagingSenderId: '860153483862',
    projectId: 'todoapp-c455a',
    storageBucket: 'todoapp-c455a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSDZgI0qMkFLMHZVINjGEflzrGxhX6kNI',
    appId: '1:860153483862:ios:3be9c49e918f27dfdce1f7',
    messagingSenderId: '860153483862',
    projectId: 'todoapp-c455a',
    storageBucket: 'todoapp-c455a.firebasestorage.app',
    iosBundleId: 'com.example.pizzeria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSDZgI0qMkFLMHZVINjGEflzrGxhX6kNI',
    appId: '1:860153483862:ios:3be9c49e918f27dfdce1f7',
    messagingSenderId: '860153483862',
    projectId: 'todoapp-c455a',
    storageBucket: 'todoapp-c455a.firebasestorage.app',
    iosBundleId: 'com.example.pizzeria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNpNxi4xczl7RqI1al8cVbvr-ttkWNOFk',
    appId: '1:860153483862:web:54d50727faa37127dce1f7',
    messagingSenderId: '860153483862',
    projectId: 'todoapp-c455a',
    authDomain: 'todoapp-c455a.firebaseapp.com',
    storageBucket: 'todoapp-c455a.firebasestorage.app',
    measurementId: 'G-1GB9TLT9B8',
  );
}
